// <auto-generated />
using System;
using MediatRDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediatRDemo.Data.Migrations
{
    [DbContext(typeof(MediatRDbContext))]
    partial class MediatRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MediatRDemo.Data.Models.Department", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UIX_Department_Name")
                        .IsUnique();

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Account"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Human Resource"
                        });
                });

            modelBuilder.Entity("MediatRDemo.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte>("DepartmentId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = (byte)3,
                            Name = "John",
                            Salary = 25000
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = (byte)3,
                            ManagerId = 1,
                            Name = "Robert",
                            Salary = 15000
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = (byte)2,
                            ManagerId = 2,
                            Name = "Richard",
                            Salary = 10000
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = (byte)2,
                            ManagerId = 3,
                            Name = "Mark",
                            Salary = 7500
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = (byte)1,
                            ManagerId = 2,
                            Name = "Stefan",
                            Salary = 5000
                        });
                });

            modelBuilder.Entity("MediatRDemo.Data.Models.Employee", b =>
                {
                    b.HasOne("MediatRDemo.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediatRDemo.Data.Models.Employee", "Manager")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MediatRDemo.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("MediatRDemo.Data.Models.Employee", b =>
                {
                    b.Navigation("ManagedEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
